### PR TITLE
Allow user to enable/disable progress bars

### LINKED ISSUE #44: Endless progress bars for endless (but complete) spark jobs
There have been cases where the Spark StatusTracker believes a job is still in progress when in fact it has completed and returned results to the driver. When this happens (and surely it's some kind of Spark bug that it does), the progress thread continually outputs useless progress information.

It's not clear how to filter out these dead jobs. Minimally we should consider having a way of turning the progress bars off / on at runtime without hacking `sc._jsc = None` to get the thread to quit. This is clearly stopgap: we should figure out what's causing the bug and get it fixed upstream.

### PR DESCRIPTION
**Pull request by parente**
Fixes #44. I want to see how Python 3.6 runs on travis.
I got a SystemError about a NULL from CPython from the
defaultdict in the ProgressThread in py3.6 on my Mac.
Python 3.5 worked fine. Oh boy!

### CODE REVIEW

**Comment by parente** [comment]
Interesting. Same Python 3.6 failure on travis:

```
Traceback (most recent call last):
    File "/home/travis/miniconda/envs/testenv/lib/py...-in method __missing__ of collections.defaultdict object at 0x7f65e0fcc4f8> returned NULL without setting an error
```

That seems *really* low level.

**Comment by mariusvniekerk** [comment]
I guess replace it with a normal dictionary which kinda sucks?

**Comment by parente** [comment]
http://bugs.python.org/issue30473 with simpler reproducible test case.

Workaround: wrapping it in a lambda avoids the problem.

**Comment by parente** [comment]
Going to try to bump up the test coverage a bit more on the progress module before calling it ready.

**Pull request merged**
