### PR TITLE
Unlink fix

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Added some more tests for deletion and fixed incorrect usage of os.unlink

### CODE REVIEW

**Comment by parente** [comment]
Might be a race condition in that test or some other dep. It failed after merge to master on popen.

**Comment by mariusvniekerk** [comment]
Weird

**Comment by mariusvniekerk** [comment]
Failed on the conda create.  Could be that anaconda.org was having some problems?

**Comment by parente** [comment]
Yea. True. The release tag tested fine so we'll just keep an eye on it.

**Pull request merged**
