### PR TITLE
Added doctr to travis build.

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Let's see if this works.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@ericdill @parente Not entirely sure why the sphinx stuff is moaning.

**Comment by parente** [comment]
@mariusvniekerk Try adding a blank line between "Complete Reference (API)" and the line above it.

If you make your PR writable, I can experiment if that newline doesn't solve it.

**Comment by parente** [comment]
The whitespace fix has to go in the bash readme hack script. There's other problems after that as well.

I tried to push to your branch but can't.  Can you check the access permissions?

**Comment by parente** [comment]
There's various deps missing that are causing imports to fail: pandas, pyyaml.

**Comment by mariusvniekerk** [comment]
Looks like we're green now.   Anything else we want to add here ?

**Comment by parente** [comment]
Is it posting to RTFD properly? If so, :shipit:

**Comment by mariusvniekerk** [comment]
Well it pushes to gh pages.  But should be fine.

**Comment by mariusvniekerk** [comment]
https://travis-ci.org/MaxPoint/spylon/jobs/160656977#L758

Looks like the hackery we do with index.rst confuses it.  I'll make a follow-on

**Comment by mariusvniekerk** [comment]
Follow on in #17

**Pull request merged**
