### PR TITLE
CI: Always build docs. Tweak to deploy correctly

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
Once again I pushed to origin by accident 🤦‍♂️

**Comment by ericdill** [comment]
. Ignore the failed CI/travis-ci/push ❌

**Comment by ericdill** [comment]
Closes #46 🤞

**Comment by parente** [comment]
Thanks for the quick fix. Let's find out by merging to master!

**Comment by parente** [comment]
No such luck: https://travis-ci.org/maxpoint/spylon/builds/235685516

**Pull request merged**
